#!/usr/bin/env python

import sys
from os import remove, removedirs
from os.path import dirname, join, isfile
from time import time

topMovies = """1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
110,Braveheart (1995),Action|Drama|War
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
318,Shawshank Redemption, The (1994),Crime|Drama
356,Forrest Gump (1994),Comedy|Drama|Romance|War
480,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller
527,Schindler's List (1993),Drama|War
593,Silence of the Lambs, The (1991),Crime|Horror|Thriller
2571,Matrix, The (1999),Action|Sci-Fi|Thriller"""

parentDir = dirname(dirname(__file__))
ratingsFile = join(parentDir, "personalRatings.txt")

if isfile(ratingsFile):
    r = raw_input("Looks like you've already rated the movies. Overwrite ratings (y/N)? ")
    if r and r[0].lower() == "y":
        remove(ratingsFile)
    else:
        sys.exit()

prompt = "Please rate the following movie (1-5 (best), or 0 if not seen): "
print prompt

now = int(time())
n = 0

f = open(ratingsFile, 'w')
for line in topMovies.split("\n"):
    ls = line.strip().split(",")
    valid = False
    while not valid:
        rStr = raw_input(ls[1] + ": ")
        r = int(rStr) if rStr.isdigit() else -1
        if r < 0 or r > 5:
            print prompt
        else:
            valid = True
            if r > 0:
                f.write("0,%s,%d,%d\n" % (ls[0], r, now))
                n += 1
f.close()

if n == 0:
    print "No rating provided!"
